### ISSUE TITLE
Exception #0 (Magento\Framework\Exception\NoSuchEntityException): The entity that was requested doesn't exist. Verify the entity and try again.

### ISSUE THREAD

**Issue by JainSoftware** [Apptha/Marketplace-M2#25]
Case : When creating account at time of order . This issue happening when we enabling Apptha Marketsplace extension and at time of order creating new account .

Exception #0 (Magento\Framework\Exception\NoSuchEntityException): The entity that was requested doesn't exist. Verify the entity and try again.
#0 /home2/jainsoftware/public_html/vendor/magento/framework/Interception/Interceptor.php(58): Magento\Sales\Model\OrderRepository->get('47')
#1 /home2/jainsoftware/public_html/vendor/magento/framework/Interception/Interceptor.php(138): Magento\Sales\Model\OrderRepository\Interceptor->___callParent('get', Array)
#2 /home2/jainsoftware/public_html/vendor/magento/framework/Interception/Interceptor.php(153): Magento\Sales\Model\OrderRepository\Interceptor->Magento\Framework\Interception\{closure}('47')
#3 /home2/jainsoftware/public_html/generated/code/Magento/Sales/Model/OrderRepository/Interceptor.php(26): Magento\Sales\Model\OrderRepository\Interceptor->___callPlugins('get', Array, Array)
#4 /home2/jainsoftware/public_html/vendor/magento/module-checkout/Block/Registration.php(120): Magento\Sales\Model\OrderRepository\Interceptor->get('47')
#5 /home2/jainsoftware/public_html/vendor/magento/module-checkout/Block/Registration.php(106): Magento\Checkout\Block\Registration->validateAddresses()
#6 /home2/jainsoftware/public_html/vendor/magento/framework/View/Layout.php(557): Magento\Checkout\Block\Registration->toHtml()
#7 /home2/jainsoftware/public_html/vendor/magento/framework/View/Layout.php(533): Magento\Framework\View\Layout->_renderBlock('checkout.regist...')
#8 /home2/jainsoftware/public_html/generated/code/Magento/Framework/View/Layout/Interceptor.php(206): Magento\Framework\View\Layout->renderNonCachedElement('checkout.regist...')
#9 /home2/jainsoftware/public_html/vendor/magento/framework/View/Layout.php(488): Magento\Framework\View\Layout\Interceptor->renderNonCachedElement('checkout.regist...')
#10 /home2/jainsoftware/public_html/generated/code/Magento/Framework/View/Layout/Interceptor.php(193): Magento\Framework\View\Layout->renderElement('checkout.regist...', false)
#11 /home2/jainsoftware/public_html/vendor/magento/framework/View/Layout.php(585): Magento\Framework\View\Layout\Interceptor->renderElement('checkout.regist...', false)
#12 /home2/jainsoftware/public_html/vendor/magento/framework/View/Layout.php(535): Magento\Framework\View\Layout->_renderContainer('content', false)
#13 /home2/jainsoftware/public_html/generated/code/Magento/Framework/View/Layout/Interceptor.php(206): Magento\Framework\View\Layout->renderNonCachedElement('content')
#14 /home2/jainsoftware/public_html/vendor/magento/framework/View/Layout.php(488): Magento\Framework\View\Layout\Interceptor->renderNonCachedElement('content')
#15 /home2/jainsoftware/public_html/generated/code/Magento/Framework/View/Layout/Interceptor.php(193): Magento\Framework\View\Layout->renderElement('content', false)
#16 /home2/jainsoftware/public_html/vendor/magento/framework/View/Layout.php(585): Magento\Framework\View\Layout\Interceptor->renderElement('content', false)
#17 /home2/jainsoftware/public_html/vendor/magento/framework/View/Layout.php(535): Magento\Framework\View\Layout->_renderContainer('main', false)
#18 /home2/jainsoftware/public_html/generated/code/Magento/Framework/View/Layout/Interceptor.php(206): Magento\Framework\View\Layout->renderNonCachedElement('main')
#19 /home2/jainsoftware/public_html/vendor/magento/framework/View/Layout.php(488): Magento\Framework\View\Layout\Interceptor->renderNonCachedElement('main')
#20 /home2/jainsoftware/public_html/generated/code/Magento/Framework/View/Layout/Interceptor.php(193): Magento\Framework\View\Layout->renderElement('main', false)
#21 /home2/jainsoftware/public_html/vendor/magento/framework/View/Layout.php(585): Magento\Framework\View\Layout\Interceptor->renderElement('main', false)
#22 /home2/jainsoftware/public_html/vendor/magento/framework/View/Layout.php(535): Magento\Framework\View\Layout->_renderContainer('columns', false)
#23 /home2//public_html/generated/code/Magento/Framework/View/Layout/Interceptor.php(206): Magento\Framework\View\Layout->renderNonCachedElement('columns')
#24 /home2/jainsoftware/public_html/vendor/magento/framework/View/Layout.php(488): Magento\Framework\View\Layout\Interceptor->renderNonCachedElement('columns')
#25 /home2/jainsoftware/public_html/generated/code/Magento/Framework/View/Layout/Interceptor.php(193): Magento\Framework\View\Layout->renderElement('columns', false)
#26 /home2/jainsoftware/public_html/vendor/magento/framework/View/Layout.php(585): Magento\Framework\View\Layout\Interceptor->renderElement('columns', false)
#27 /home2/jainsoftware/public_html/vendor/magento/framework/View/Layout.php(535): Magento\Framework\View\Layout->_renderContainer('main.content', false)
#28 /home2/jainsoftware/public_html/generated/code/Magento/Framework/View/Layout/Interceptor.php(206): Magento\Framework\View\Layout->renderNonCachedElement('main.content')
#29 /home2/jainsoftware/public_html/vendor/magento/framework/View/Layout.php(488): Magento\Framework\View\Layout\Interceptor->renderNonCachedElement('main.content')
#30 /home2/jainsoftware/public_html/generated/code/Magento/Framework/View/Layout/Interceptor.php(193): Magento\Framework\View\Layout->renderElement('main.content', false)
#31 /home2/jainsoftware/public_html/vendor/magento/framework/View/Layout.php(585): Magento\Framework\View\Layout\Interceptor->renderElement('main.content', false)
#32 /home2/jainsoftware/public_html/vendor/magento/framework/View/Layout.php(535): Magento\Framework\View\Layout->_renderContainer('page.wrapper', false)
#33 /home2/jainsoftware/public_html/generated/code/Magento/Framework/View/Layout/Interceptor.php(206): Magento\Framework\View\Layout->renderNonCachedElement('page.wrapper')
#34 /home2/jainsoftware/public_html/vendor/magento/framework/View/Layout.php(488): Magento\Framework\View\Layout\Interceptor->renderNonCachedElement('page.wrapper')
#35 /home2/jainsoftware/public_html/generated/code/Magento/Framework/View/Layout/Interceptor.php(193): Magento\Framework\View\Layout->renderElement('page.wrapper', false)
#36 /home2/jainsoftware/public_html/vendor/magento/framework/View/Layout.php(585): Magento\Framework\View\Layout\Interceptor->renderElement('page.wrapper', false)
#37 /home2/jainsoftware/public_html/vendor/magento/framework/View/Layout.php(535): Magento\Framework\View\Layout->_renderContainer('root', false)
#38 /home2/jainsoftware/public_html/generated/code/Magento/Framework/View/Layout/Interceptor.php(206): Magento\Framework\View\Layout->renderNonCachedElement('root')
#39 /home2/jainsoftware/public_html/vendor/magento/framework/View/Layout.php(488): Magento\Framework\View\Layout\Interceptor->renderNonCachedElement('root')
#40 /home2/jainsoftware/public_html/generated/code/Magento/Framework/View/Layout/Interceptor.php(193): Magento\Framework\View\Layout->renderElement('root', true)
#41 /home2/jainsoftware/public_html/vendor/magento/framework/View/Layout.php(954): Magento\Framework\View\Layout\Interceptor->renderElement('root')
#42 /home2/jainsoftware/public_html/vendor/magento/framework/Interception/Interceptor.php(58): Magento\Framework\View\Layout->getOutput()
#43 /home2/jainsoftware/public_html/vendor/magento/framework/Interception/Interceptor.php(138): Magento\Framework\View\Layout\Interceptor->___callParent('getOutput', Array)
#44 /home2/jainsoftware/public_html/vendor/magento/framework/Interception/Interceptor.php(153): Magento\Framework\View\Layout\Interceptor->Magento\Framework\Interception\{closure}()
#45 /home2/jainsoftware/public_html/generated/code/Magento/Framework/View/Layout/Interceptor.php(494): Magento\Framework\View\Layout\Interceptor->___callPlugins('getOutput', Array, Array)
#46 /home2/jainsoftware/public_html/vendor/magento/framework/View/Result/Page.php(258): Magento\Framework\View\Layout\Interceptor->getOutput()
#47 /home2/jainsoftware/public_html/vendor/magento/framework/View/Result/Layout.php(171): Magento\Framework\View\Result\Page->render(Object(Magento\Framework\App\Response\Http\Interceptor))
#48 /home2/jainsoftware/public_html/vendor/magento/framework/Interception/Interceptor.php(58): Magento\Framework\View\Result\Layout->renderResult(Object(Magento\Framework\App\Response\Http\Interceptor))
#49 /home2/jainsoftware/public_html/vendor/magento/framework/Interception/Interceptor.php(138): Magento\Framework\View\Result\Page\Interceptor->___callParent('renderResult', Array)
#50 /home2/jainsoftware/public_html/vendor/magento/framework/Interception/Interceptor.php(153): Magento\Framework\View\Result\Page\Interceptor->Magento\Framework\Interception\{closure}(Object(Magento\Framework\App\Response\Http\Interceptor))
#51 /home2/jainsoftware/public_html/generated/code/Magento/Framework/View/Result/Page/Interceptor.php(130): Magento\Framework\View\Result\Page\Interceptor->___callPlugins('renderResult', Array, Array)
#52 /home2/jainsoftware/public_html/vendor/magento/framework/App/Http.php(139): Magento\Framework\View\Result\Page\Interceptor->renderResult(Object(Magento\Framework\App\Response\Http\Interceptor))
#53 /home2/jainsoftware/public_html/generated/code/Magento/Framework/App/Http/Interceptor.php(24): Magento\Framework\App\Http->launch()
#54 /home2/jainsoftware/public_html/vendor/magento/framework/App/Bootstrap.php(258): Magento\Framework\App\Http\Interceptor->launch()
#55 /home2/jainsoftware/public_html/index.php(39): Magento\Framework\App\Bootstrap->run(Object(Magento\Fram

Exception #0 (Magento\Framework\Exception\NoSuchEntityException): The entity that was requested doesn't exist. Verify the entity and try again.

**Comment by orloopssolutions** [comment]
buddy, do the file permission correctly. Apptha perfectly works on PHP 7.1 and Magento 2.2

**Comment by orloopssolutions** [comment]
https://github.com/Apptha/Marketplace-M2/issues/26

**Comment by VishalParkash** [comment]
> o the file permission correctly

Is it really permission issue? I am using php 7.4 with magento 2.4.0
